# Generated by Django 4.1.5 on 2024-10-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacultyName', models.CharField(max_length=255)),
                ('FID', models.CharField(max_length=255)),
            ],
        ),
    ]
