# Generated by Django 4.1.5 on 2024-09-24 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsApp', '0003_semester'),
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Sem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DetailsApp.department'),
        ),
    ]
