# Generated by Django 4.1.5 on 2024-10-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsApp', '0003_semester'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
